# Generated by Django 5.1.4 on 2025-01-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team1', models.CharField(choices=[('mi', 'MI'), ('rcb', 'RCB'), ('csk', 'CSK'), ('kkr', 'KKR'), ('rr', 'RR')], max_length=50)),
                ('team2', models.CharField(choices=[('mi', 'MI'), ('rcb', 'RCB'), ('csk', 'CSK'), ('kkr', 'KKR'), ('rr', 'RR')], max_length=50)),
                ('inning', models.IntegerField(choices=[(1, 1), (2, 2)])),
            ],
        ),
    ]
