# Generated by Django 5.1.4 on 2025-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(choices=[(1, 'Go to Market'), (2, 'Buy Vegetables'), (3, 'Pay Money'), (4, 'Return Home')], max_length=50)),
                ('isCompleted', models.BooleanField()),
            ],
        ),
    ]
